"""store provider sensor handles

Revision ID: cce77c145b0a
Revises: f1cd88ae6171
Create Date: 2026-09-06 08:07:28.206239+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cce77c145b0a'
down_revision: Union[str, None] = 'f1cd88ae6171'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # A server default is required: without it this fails on any table that
    # already has rows, because existing stations have no value to write.
    op.add_column(
        "stations",
        sa.Column(
            "sensor_ids",
            sa.JSON(),
            nullable=False,
            server_default=sa.text("'{}'::json"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stations', 'sensor_ids')
    # ### end Alembic commands ###
