"""initial schema

Revision ID: f1cd88ae6171
Revises: 
Create Date: 2026-09-06 07:54:23.536174+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1cd88ae6171'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('algorithm', sa.String(length=80), nullable=False),
    sa.Column('trained_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('training_rows', sa.Integer(), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('feature_names', sa.JSON(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('artifact_path', sa.String(length=400), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.String(length=400), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'version', name='uq_model_name_version')
    )
    op.create_index('uq_model_single_active', 'model_versions', ['name'], unique=True, postgresql_where=sa.text('is_active IS true'))
    op.create_table('stations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=16), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('city_slug', sa.String(length=40), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('elevation_m', sa.Float(), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('latitude BETWEEN -90 AND 90', name='ck_station_latitude'),
    sa.CheckConstraint('longitude BETWEEN -180 AND 180', name='ck_station_longitude'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'external_id', name='uq_station_provider_external')
    )
    op.create_index('ix_station_lat_lon', 'stations', ['latitude', 'longitude'], unique=False)
    op.create_index(op.f('ix_stations_city_slug'), 'stations', ['city_slug'], unique=False)
    op.create_table('ambient_conditions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('valid_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_forecast', sa.Boolean(), nullable=False),
    sa.Column('cams_pm25', sa.Float(), nullable=True),
    sa.Column('cams_pm10', sa.Float(), nullable=True),
    sa.Column('temperature_c', sa.Float(), nullable=True),
    sa.Column('relative_humidity', sa.Float(), nullable=True),
    sa.Column('wind_speed_ms', sa.Float(), nullable=True),
    sa.Column('wind_direction_deg', sa.Float(), nullable=True),
    sa.Column('precipitation_mm', sa.Float(), nullable=True),
    sa.Column('pressure_hpa', sa.Float(), nullable=True),
    sa.Column('boundary_layer_m', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('station_id', 'valid_at', name='uq_ambient_natural_key')
    )
    op.create_index('ix_ambient_station_time', 'ambient_conditions', ['station_id', 'valid_at'], unique=False)
    op.create_table('forecasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('model_version_id', sa.Integer(), nullable=True),
    sa.Column('estimator', sa.String(length=16), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('horizon_hours', sa.Integer(), nullable=False),
    sa.Column('pm25', sa.Float(), nullable=False),
    sa.Column('pm25_low', sa.Float(), nullable=True),
    sa.Column('pm25_high', sa.Float(), nullable=True),
    sa.CheckConstraint('horizon_hours BETWEEN 1 AND 120', name='ck_forecast_horizon'),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('station_id', 'estimator', 'issued_at', 'valid_at', name='uq_forecast_natural_key')
    )
    op.create_index('ix_forecast_issued', 'forecasts', ['issued_at'], unique=False)
    op.create_index('ix_forecast_station_valid', 'forecasts', ['station_id', 'valid_at'], unique=False)
    op.create_table('measurements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('parameter', sa.String(length=8), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('value >= 0', name='ck_measurement_non_negative'),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('station_id', 'parameter', 'observed_at', name='uq_measurement_natural_key')
    )
    op.create_index('ix_measurement_station_time', 'measurements', ['station_id', 'observed_at'], unique=False)
    op.create_index('ix_measurement_time', 'measurements', ['observed_at'], unique=False)
    op.create_table('model_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_version_id', sa.Integer(), nullable=True),
    sa.Column('estimator', sa.String(length=16), nullable=False),
    sa.Column('scored_on', sa.Date(), nullable=False),
    sa.Column('horizon_hours', sa.Integer(), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('mae', sa.Float(), nullable=False),
    sa.Column('rmse', sa.Float(), nullable=False),
    sa.Column('bias', sa.Float(), nullable=False),
    sa.Column('coverage_80', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_version_id', 'estimator', 'scored_on', 'horizon_hours', name='uq_score_natural_key')
    )
    op.create_index('ix_score_scored_on', 'model_scores', ['scored_on'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_score_scored_on', table_name='model_scores')
    op.drop_table('model_scores')
    op.drop_index('ix_measurement_time', table_name='measurements')
    op.drop_index('ix_measurement_station_time', table_name='measurements')
    op.drop_table('measurements')
    op.drop_index('ix_forecast_station_valid', table_name='forecasts')
    op.drop_index('ix_forecast_issued', table_name='forecasts')
    op.drop_table('forecasts')
    op.drop_index('ix_ambient_station_time', table_name='ambient_conditions')
    op.drop_table('ambient_conditions')
    op.drop_index(op.f('ix_stations_city_slug'), table_name='stations')
    op.drop_index('ix_station_lat_lon', table_name='stations')
    op.drop_table('stations')
    op.drop_index('uq_model_single_active', table_name='model_versions', postgresql_where=sa.text('is_active IS true'))
    op.drop_table('model_versions')
    # ### end Alembic commands ###
